export const SHOW_LOADING = 'ui/SHOW_LOADING'
export const HIDDEN_LOADING = 'ui/HIDDEN_LOADING'

export const SHOW_ORDER_PRODUCT = 'ui/SHOW_ORDER_PRODUCT'
export const HIDDEN_MODAL = 'ui/HIDDEN_MODAL'

export const SHOW_ACTIVE_SEARCH = 'ui/SHOW_ACTIVE_SEARCH'
