export const GET_MORE = 'GET_MORE';
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';
export const ERROR_PRODUCT = 'ERROR_PRODUCT';
export const GET_PRODUCT_FROM_CATEGORY = 'GET_PRODUCT_FROM_CATEGORY'
export const GET_PRODUCT_FROM_COLOR = 'GET_PRODUCT_FROM_COLOR'
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'